### PR TITLE
Feature packet improvements

### PR DESCRIPTION
**Pull request by whoenig**
This PR contains a number of commits with small bugfixes and an improved interface:

1. CMake: avoid building pybind11 targets by default. [Feature]
2. Packet interface: add new helper functions to simplify creating CRTP packets [Feature]
3. Statistics: Proper update of enqueued_count [Bugfix]

See also https://github.com/IMRCLab/crazyswarm2/issues/5.

### CODE REVIEW

**Comment by knmcguire** [comment]
I've looked at the changes and tried out the code so to me it all looks good. I also haven't helped setting up this code, so bit unsure if I have the right eye on to really evaluate this PR.

 I've just tried the example_scan and example_console but is there anything I should look out for to make sure that this PR is doing it's purpose? The most important one is to see if enqueued_count is fixed right?

**Comment by whoenig** [comment]
I don't think you would see any functional changes here, because enqueued_count was simply not used in the example applications.
There is no really good reviewer - Arnaud helped a lot with the CI infrastructure, but otherwise the code wasn't reviewed much.

**Comment by knmcguire** [comment]
Yeah true. And the changes you have implement would not have a major impact on the functionality, mostly statistic related.

I've just added the next release milestone on it, but if you want you can go ahead and merge it.

**Comment by knmcguire** [comment]
Or I'll merge it:) here you go!

**Comment by whoenig** [comment]
Thanks! I'll update the other projects recursively.

**Pull request merged**
