### PR TITLE
Attempt to improve locking granularity

### PR DESCRIPTION
**Pull request by jonasdn**
- radio thread: Do not hold mutex across sendPacket
- Connection: make counters std::atomic

Fixes: #10

### CODE REVIEW

**Comment by ataffanel** [comment]
I think I see a bug: the link must guarantee packet ordering within port. This means that we cannot push back a packet in the queue if we have released the lock, it is possible that the client would have pushed a packet in the mean-time and this will break the packet ordering. This is likely why this lock was hold for so long.

A proposal would be to store the not-yet-sent packet in another variable in the connection object, this is what I have been doing in the rust link. This is not reproducing exactly the previous behavior: in the previous behavior a higher-priority packet could interleave the retry and so it had potentially lower latency, but I do not think this will be noticeable practically.

**Comment by jonasdn** [comment]
> I think I see a bug: the link must guarantee packet ordering within port. This means that we cannot push back a packet in the queue if we have released the lock, it is possible that the client would have pushed a packet in the mean-time and this will break the packet ordering. This is likely why this lock was hold for so long.
> 
> A proposal would be to store the not-yet-sent packet in another variable in the connection object, this is what I have been doing in the rust link. This is not reproducing exactly the previous behavior: in the previous behavior a higher-priority packet could interleave the retry and so it had potentially lower latency, but I do not think this will be noticeable practically.

I've tried to address this in the commit 9809a713d329bdd5e7b19bb8d7b3df8b3fe34221, does it look sane?

**Review by whoenig — APPROVED** [review]
This looks great. I agree that this is a slight behavior change, but I think it makes more sense this way.

Good idea to switch to std::atomic for the statistics!

**Comment by ataffanel** [comment]
I have seen one case of failed/corrupted flashing with this branch (the first time I tried ...). I am investigating to see if there is anything that could have caused it.

**Comment by whoenig** [comment]
There was some sort of error message, or the data that was written did not verify after a readback?

**Comment by jonasdn** [comment]
> I have seen one case of failed/corrupted flashing with this branch (the first time I tried ...). I am investigating to see if there is anything that could have caused it.

I might've seen this as well, problem after flash, self-test failing. What did you see?

**Comment by ataffanel** [comment]
> There was some sort of error message, or the data that was written did not verify after a readback?

I got a hardfault after flashing and it disapeared after flashing a second time the same firmware. This is not something that I have seen recently with the python link so it could be something going wrong in the communication loop.

**Comment by whoenig** [comment]
FYI: when I had issues with flashing last time, I used a JTAG adapter to read back the written image. The difference between the desired and written image can give some insights on why there was an issue in the first place.
Do we already have a story/issue for adding a verification function for flashing?

**Comment by jonasdn** [comment]
> FYI: when I had issues with flashing last time, I used a JTAG adapter to read back the written image. The difference between the desired and written image can give some insights on why there was an issue in the first place.
> Do we already have a story/issue for adding a verification function for flashing?

No we do not, I think adding a positional boolean argument `verify` to the `flash_full` method of the python lib would make sense for debug. Even if it will be very slow without checksum.

I will also try to write some radio debug app (app-layer) to see if we can find issues with the link libraries.

**Comment by knmcguire** [comment]
what shall we do with this PR  you think @whoenig ? Jonas will not be able to finish this but it had some nice features to it though.

**Comment by krichardsson** [comment]
@whoenig @ataffanel I would like to close this PR as no progress has been made. It seems as you would like to extract some parts of the code though, how do you want to handle this?
Close the PR (the branch will still be around)?

**Pull request closed without merging**
