### PR TITLE
Merging Develop into Master, Moved all Methods into a Single Class Named 'Crazyflie'

### PR DESCRIPTION
**Pull request by trakevital**

### CODE REVIEW

**Comment by whoenig** [comment]
I understand that this is still work in progress, but I want to provide a warning regardless: crazyflie-link-cpp was never intended to replace crazyflie-cpp (or be a C++ rewrite of the Python lib). It is supposed to purely focus on the low-level communication (link layer) and not have any knowledge about higher protocols. Thus, we are not planning to add any support for any Crazyflie-specific, high-level functions in this library.

Longer term, crazyflie-cpp is going to switch to crazyflie-link-cpp and then all crazyflie-specific code is planned to go in there. Perhaps we can discuss your high-level use-case/goals here first?

**Comment by trakevital** [comment]
> I understand that this is still work in progress, but I want to provide a warning regardless: crazyflie-link-cpp was never intended to replace crazyflie-cpp (or be a C++ rewrite of the Python lib). It is supposed to purely focus on the low-level communication (link layer) and not have any knowledge about higher protocols. Thus, we are not planning to add any support for any Crazyflie-specific, high-level functions in this library.
> 
> Longer term, crazyflie-cpp is going to switch to crazyflie-link-cpp and then all crazyflie-specific code is planned to go in there. Perhaps we can discuss your high-level use-case/goals here first?

I see your point, we arecurrently planning on using your repo as a submodule in our own crazyflie-lib-cpp project.

I also believe that this pull request was done by accident will let you know soon enough

**Comment by whoenig** [comment]
Closing, since the plan is to use this repo as a submodule for higher-level functionality.

**Comment by trakevital** [comment]
Yes this was a mistake and good thing you closed it

**Pull request closed without merging**
